Salsa-Dancing-Molecules/Salsa-Dancing-Molecules

- .github/workflows/lint.yml
- salsa_dancing_molecules/__init__.py
- salsa_dancing_molecules/cli/__init__.py
- salsa_dancing_molecules/cli/main.py
Create a Github action that lints the code using pycodestyle and pydocstyle on each push.
> CI: Create Github action to lint the code

- salsa_dancing_molecules/mock_atoms.py
- salsa_dancing_molecules/pressure.py
- salsa_dancing_molecules/temperature.py
- salsa_dancing_molecules/unittest_pressure.py
Created a file for calculating pressure. Also created a test-file aswell as an mock-object for atoms. These files have been used to unittest the function and it works as intended.
> Add function for calculating pressure.

- .github/workflows/unit_tests.yml
- README.md
- salsa_dancing_molecules/unit_test/test_example.py
- setup.py
Add a Gitlab workflow to run unit tests in the CI.
> Run unit tests in CI

- .github/workflows/unit_tests.yml
- salsa_dancing_molecules/calculator/__init__.py
- salsa_dancing_molecules/calculator/capacity_NVE.py
- salsa_dancing_molecules/calculator/capacity_NVT.py
- salsa_dancing_molecules/calculator/energies_ensamble.py
- salsa_dancing_molecules/unit_test/__init__.py
- salsa_dancing_molecules/unit_test/test_capacity.py
Two files for calculation of heat capacity for NVE resp. NVT ensemble and an test file for unit-tests. Added an empty file 'energies_ensemble' that in the future will calculate the ensemble average energies.
> Add calculations for heat capacity

- salsa_dancing_molecules/materialsproject.py
- setup.py
This adds a class that allows fetching materials from materialsproject.org.
> Class for fetching from materialsproject

- salsa_dancing_molecules/force.py
- salsa_dancing_molecules/unit_test/test_force.py
Create a file for calculating force.
Create a test-file and a mock-object for force function.
> Create module for calculating forces.

- salsa_dancing_molecules/energy.py
- salsa_dancing_molecules/unit_test/mock_atoms.py
- salsa_dancing_molecules/unit_test/test_energy.py
Added functions to calculate potential, kinetic and total energy.
> Energy calculation

- LennardJones612_UniversalShifted.params
- salsa_dancing_molecules/lennardjonesparse.py
- salsa_dancing_molecules/unit_test/test_lj.py
Add unit test for this function.
> Add Lennard-Jones parameter parseer for arbitrary element. 

- salsa_dancing_molecules/unit_test/test_temperature.py
The test is randomly failing. Disable it for now and fix it later.
> unit_tests: temperature: disable randomly failing test

- salsa_dancing_molecules/mean_square_displacement.py
- salsa_dancing_molecules/unit_test/test_msd.py
Also create test function for mean square displacement using mock objects. Mean square displacement function has also been tested using real trajectory file.
co-author: Kristofer Gubberud Maras <krima334@student.liu.se>
co-author: Anton Skott <antsk499@student.liu.se>
> Create function for mean square displacement.

- salsa_dancing_molecules/cli/main.py
- salsa_dancing_molecules/filerwriter.py
- salsa_dancing_molecules/pressure.py
- salsa_dancing_molecules/simulations/nve.py
- salsa_dancing_molecules/variables.py
Parametrization of the argon example is complete. It saves a set of data to a CSV file.
> Parametrization of the argon example

- salsa_dancing_molecules/mean_square_displacement.py
- salsa_dancing_molecules/self_diffusion_coefficient.py
- salsa_dancing_molecules/unit_test/test_self_diffusion.py
Author Anton Skott <antsk499@student.liu.se>
Co-author Kristoffer G Maras <krima334@student.liu.se>
> Create a module for self diffusion coefficient

- salsa_dancing_molecules/unit_test/test_temperature.py
Temperature function test is now deterministic 🥳.
> Temperature function test fix

- example_simulation/simulation_config.conf
- example_simulation/simulation_config_materialsproject.conf
- salsa_dancing_molecules/startup/startup_script.py
- salsa_dancing_molecules/worker_process/worker_process.py
Small fix-ups for path handling in the start script.
> Path handling fixes

- salsa_dancing_molecules/debye_temperature.py
- salsa_dancing_molecules/unit_test/test_debye_temperature.py
Co Author Anton Skott <antsk499@student.liu.se>
>  Create a function for calculating the debye temperature

- example_simulation/simulation_config.conf
- salsa_dancing_molecules/simulations/simulation.py
- salsa_dancing_molecules/unit_test/test_generate_json.py
- salsa_dancing_molecules/worker_process/simulation_starter.py
- salsa_dancing_molecules/worker_process/worker_process.py
Implement new simulation file for worker process with openkim, nve and nvt.
> Worker simulation

- salsa_dancing_molecules/capacity_NVE.py
- salsa_dancing_molecules/capacity_NVT.py
- salsa_dancing_molecules/pressure.py
- salsa_dancing_molecules/unit_test/test_capacity.py
- salsa_dancing_molecules/unit_test/test_pressure.py
Change units of pressure to Pa and och special heat capacity to J / (K * kg)
> Pressure and special heat capacity unit fix

- salsa_dancing_molecules/lindemann.py
- salsa_dancing_molecules/unit_test/test_lindemann.py
Calculate the Lindemann parameter and check if the Lindemann criterion is violated.
> Add calculation for Lindemann.

- salsa_dancing_molecules/cohesive_energy.py
Move some calculations from get_cohesive_energy() to calculate_cohesive_energy().
> Rearrenge calculations in cohesive_energy.

- salsa_dancing_molecules/cli/main.py
- salsa_dancing_molecules/ensemble_energies.py
- salsa_dancing_molecules/equilibrium.py
- salsa_dancing_molecules/post_process/post_process.py
- salsa_dancing_molecules/post_process/post_simulation_calculation.py
- salsa_dancing_molecules/simulations/simulation.py
Co-authors: Anton Skott <antsk499@student.liu.se>, Edvard Valentin <edvva488@student.liu.se>, Hilma Karlsson <hilka588@student.liu.se>
> Create module for calculating the post simulation values.

- example_simulation/simulation_config.conf
- salsa_dancing_molecules/post_process/post_process.py
- salsa_dancing_molecules/simulations/simulation.py
- salsa_dancing_molecules/worker_process/worker_process.py
Co-author: Olle Nyqvist <ollny930@student.liu.se>
> Worker process perform post simulation calculations.

- salsa_dancing_molecules/bulk_properties.py
- salsa_dancing_molecules/cli/main.py
- salsa_dancing_molecules/equilibrium.py
- salsa_dancing_molecules/post_process/post_simulation_calculation.py
- salsa_dancing_molecules/volume_process/__init__.py
- salsa_dancing_molecules/volume_process/volume_process.py
Process for handling volume-simulation and calculation of bulk properties.
> Volume simulation

- salsa_dancing_molecules/startup/prepare_workspace.py
- salsa_dancing_molecules/worker_process/worker_process.py
The file was kind of hard to read now that I need to work with it so I refactored it a bit.
> worker_process: refactor file for readability

- example_simulation/argon_volume_test.conf
- salsa_dancing_molecules/bulk_properties.py
- salsa_dancing_molecules/volume_process/volume_process.py
volume process is now supposed to be used as a complete "post process" script.
> Volume process fix

- salsa_dancing_molecules/bulk_properties.py
- salsa_dancing_molecules/lindemann.py
- salsa_dancing_molecules/volume_process/volume_process.py
If not cubic cell, take unit_cell vectors as lattice constant
> volume_process: add new calculation for lattice constant

- salsa_dancing_molecules/materialsproject.py
One may now specify a Materialsproject ID in the startup configuratation, ex. 'mp_mp-1479', and it will be downloaded.
> materialsproject: allow downloading materials using their ID

- .github/workflows/unit_tests.yml
- README.md
- salsa_dancing_molecules/cli/main.py
- salsa_dancing_molecules/optimade/__init__.py
- salsa_dancing_molecules/optimade/adapters.py
- salsa_dancing_molecules/optimade/models.py
- salsa_dancing_molecules/optimade/process.py
- salsa_dancing_molecules/unit_test/test_optimade.py
- setup.py
This is a PR to add a command for exporting simulation data as OPTIMADE compatible json.
> Add OPTIMADE support

- example_simulation/simulation_config.conf
- salsa_dancing_molecules/pressure.py
- salsa_dancing_molecules/unit_test/test_pressure.py
> change pressure to proper units

- .github/workflows/lint.yml
- docs/Makefile
- docs/README
- docs/api.rst
- docs/conf.py
- docs/index.rst
- docs/make.bat
- docs/modules.rst
- docs/requirements-docs.txt
- docs/salsa_dancing_molecules.cli.rst
- docs/salsa_dancing_molecules.optimade.rst
- docs/salsa_dancing_molecules.rst
- docs/salsa_dancing_molecules.simulations.rst
- docs/salsa_dancing_molecules.startup.rst
- docs/salsa_dancing_molecules.third_party.rst
- docs/salsa_dancing_molecules.unit_test.rst
- docs/salsa_dancing_molecules.volume_process.rst
- docs/salsa_dancing_molecules.worker_process.rst
- salsa_dancing_molecules/bulk_properties.py
- salsa_dancing_molecules/cohesive_energy.py
- salsa_dancing_molecules/lindemann.py
- salsa_dancing_molecules/simulations/nve.py
- salsa_dancing_molecules/simulations/simulation.py
- salsa_dancing_molecules/volume_process/volume_process.py
- salsa_dancing_molecules/worker_process/simulation_starter.py
Docs folder taken from here: https://github.com/readthedocs/tutorial-template/
> Add docs folder from read the docs example to generate technical

- docs/salsa_dancing_molecules.post_process.rst
- docs/salsa_dancing_molecules.rst
- salsa_dancing_molecules/post_process/__init__.py
Add missing __init__.py to post_process module and add it to the documentation.
> Add post process init
